### PR TITLE
fix resize lag

### PR DESCRIPTION
**Pull request by Typhon0**
fix issue #2

### CODE REVIEW

**Comment by goxr3plus** [comment]
I can say i love  you ♥. Testing very soon and releasing the next version. THANK YOU SO MUCH.

**Comment by goxr3plus** [comment]
Did yoy twsted on Mac or Linux also :)?

**Comment by Typhon0** [comment]
Mac yes , on High Sierra but I haven't tested on Linux.

**Comment by goxr3plus** [comment]
Impressive  , just amazing i have spend many nights fixing bugs on this project but never figured it out  . Tested just now  . Just amazing i am really impressed from you :)

**Pull request merged**
